### ISSUE TITLE
where do the credentials go since update?

### ISSUE THREAD

**Issue by janusj77** [Thavarshan/jackle#1]
There seems to be no reference to config.py anywhere anymore.
Does it go in downloads or courses? is it still the same format?

if you have a working config perhaps that with blocked out user/pass that'd be awesome.

thanks :-)

**Comment by Thavarshan** [comment]
Planning for the credentials to be set in a `.env` file and the courses can be specified in the `courses.json` file. Still a work in progress, I forgot to update the `README`. I apologize for that.

You can find the original (working) repository this is based on [here](https://github.com/mypan/linkedin_learning_courses_downloader).

**Comment by janusj77** [comment]
Ah cool - thanks :-)
